### ISSUE TITLE
gather url not found error

### ISSUE THREAD

**Issue by MuhammadAdil-Developer** [avijeett007/Knotie-AI#31]
Hello I hope you are doing well today! 

I'm facing this 404 error

knotie-ai-web-1                 | INFO:     172.18.0.1:47744 - "POST //gather?CallSid=bb1b290a-875a-4535-848b-69d10b9d0478 HTTP/1.1" 404 Not Found
knotie-ai-web-1                 | INFO:     172.18.0.1:59372 - "POST //event HTTP/1.1" 404 Not Found

 when im run your knotie Ai Outbound phone calling Api
Could you plz tell me why i'm getting this error...

**Comment by avijeett007** [comment]
This issue is discussed and sorted out. Closing this issue.
